site_name: http4k Connect
site_url: https://connect.http4k.org/
site_description: http4k Connect is a lightweight API client toolkit which includes libraries for connecting to popular third-party cloud services and AI backends
site_author: David Denton (@daviddenton), Ivan Sanchez (@s4nchez)
copyright: 'Copyright &copy; 2024 - David Denton (@daviddenton), IvanSanchez (@s4nchez)'
remote_branch: master
repo_url: https://github.com/http4k/http4k-connect/
theme:
  name: 'material'
  custom_dir: ./docs/theme
  static_templates:
      - ./index.html
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue_trans.png
google_analytics: ['UA-125143867-1', 'auto']
markdown_extensions:
  - meta
  - codehilite
  - toc:
      permalink: True
      separator: "_"
extra_css:
  - ./css/site.css
extra:
  logo: img/logo_1100x200_white_on_blue_trans.png
edit_uri: edit/master/src/docs/
strict: false
nav:
  - Introduction: documentation/index.md
  - Concepts:
    - API Clients: guide/concepts/api-clients.md
    - System Fakes: guide/concepts/system-fakes.md
  - How To:
    - Implement your own API clients: guide/howto/implement-your-own-clients/index.md
    - Pimp your API clients with KSP!: guide/howto/pimp-your-clients-with-ksp/index.md
  - Module Overview: guide/reference/index.md
  - AI Reference:
    - LangChain: guide/reference/ai/langchain/index.md
    - LMStudio: guide/reference/ai/lmstudio/index.md
    - Ollama: guide/reference/ai/ollama/index.md
    - OpenAI: guide/reference/ai/openai/index.md
  - Cloud Reference:
    - AWS Overview Guide: guide/reference/amazon/index.md
    - AWS App Runner: guide/reference/amazon/apprunner/index.md
    - AWS Cloudfront: guide/reference/amazon/cloudfront/index.md
    - AWS Cloudwatch Logs: guide/reference/amazon/cloudwatchlogs/index.md
    - AWS Cognito: guide/reference/amazon/cognito/index.md
    - AWS Container Credentials: guide/reference/amazon/containercredentials/index.md
    - AWS DynamoDB: guide/reference/amazon/dynamodb/index.md
    - AWS EventBridge: guide/reference/amazon/eventbridge/index.md
    - AWS Evidently: guide/reference/amazon/evidently/index.md
    - AWS Firehose: guide/reference/amazon/firehose/index.md
    - AWS IAM Identity Center: guide/reference/amazon/iamidentitycenter/index.md
    - AWS Instance Metadata: guide/reference/amazon/instancemetadata/index.md
    - AWS KMS: guide/reference/amazon/kms/index.md
    - AWS Lambda: guide/reference/amazon/lambda/index.md
    - AWS S3: guide/reference/amazon/s3/index.md
    - AWS Secrets Manager: guide/reference/amazon/secretsmanager/index.md
    - AWS SES: guide/reference/amazon/ses/index.md
    - AWS SNS: guide/reference/amazon/sns/index.md
    - AWS SQS: guide/reference/amazon/sqs/index.md
    - AWS STS: guide/reference/amazon/sts/index.md
    - AWS Systems Manager: guide/reference/amazon/systemsmanager/index.md
    - GitHub: guide/reference/github/index.md
    - GitLab: guide/reference/gitlab/index.md
    - Google Analytics UA: guide/reference/google/analytics-ua/index.md
    - Google Analytics V4: guide/reference/google/analytics-ga4/index.md
    - Kafka REST Gateway: guide/reference/kafka/rest/index.md
    - Kafka Schema Registry: guide/reference/kafka/schemaregistry/index.md
    - Mattermost: guide/reference/mattermost/index.md
  - Storage Reference:
    - File : guide/reference/storage/core/index.md
    - HTTP: guide/reference/storage/http/index.md
    - In-Memory: guide/reference/storage/core/index.md
    - JDBC: guide/reference/storage/jdbc/index.md
    - Redis: guide/reference/storage/redis/index.md
    - S3: guide/reference/storage/s3/index.md
  - Changelog: changelog/index.md
  - Contribute/support http4k: contributing/index.md
  - Code of Conduct: code-of-conduct/index.md
